// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6WjSu71wETelQNDnmAr9TPyUio8PcUaA',
    appId: '1:70946259423:web:42b11d2e8122cce41e046a',
    messagingSenderId: '70946259423',
    projectId: 'notification-erp-72095',
    authDomain: 'notification-erp-72095.firebaseapp.com',
    storageBucket: 'notification-erp-72095.firebasestorage.app',
    measurementId: 'G-17R5B6Y5ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfKr0bbW6HIQAOg1ovU2vN1oUP_ZF31g',
    appId: '1:70946259423:android:dc49a1db4df9ff5a1e046a',
    messagingSenderId: '70946259423',
    projectId: 'notification-erp-72095',
    storageBucket: 'notification-erp-72095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkwez9-E0KiUYHlTeMSTOvPn8oOB9A88',
    appId: '1:70946259423:ios:d558588e89a349e41e046a',
    messagingSenderId: '70946259423',
    projectId: 'notification-erp-72095',
    storageBucket: 'notification-erp-72095.firebasestorage.app',
    iosBundleId: 'com.ierp.ierpMobile',
  );

}