// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wF_riP8kSiiLSojT2kAe0OwdXVz5-5E',
    appId: '1:476605524890:web:471cda610fe48ddf4e6823',
    messagingSenderId: '476605524890',
    projectId: 'sports-venue-cb204',
    authDomain: 'sports-venue-cb204.firebaseapp.com',
    storageBucket: 'sports-venue-cb204.firebasestorage.app',
    measurementId: 'G-JGM3HNSPYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpV_MJvoAsswVMjOyo4M7p5JoFko6Aoq4',
    appId: '1:476605524890:android:d3673ad3489bbb874e6823',
    messagingSenderId: '476605524890',
    projectId: 'sports-venue-cb204',
    storageBucket: 'sports-venue-cb204.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdme7MKwrjdvjoYJqKX1RKFXXvYCEtBE',
    appId: '1:476605524890:ios:bc5d72c0bc129a004e6823',
    messagingSenderId: '476605524890',
    projectId: 'sports-venue-cb204',
    storageBucket: 'sports-venue-cb204.firebasestorage.app',
    iosBundleId: 'com.ierp.ierpMobile',
  );
}
